# Generated by Django 2.2.7 on 2019-11-23 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AcceptedZakonModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reg_id', models.CharField(max_length=50)),
                ('date', models.DateField()),
                ('name', models.TextField()),
                ('number_act', models.CharField(max_length=50)),
                ('date_act', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='RegisteredZakonModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reg_id', models.CharField(max_length=50)),
                ('date', models.DateField()),
                ('name', models.TextField()),
                ('authors', models.TextField()),
            ],
        ),
    ]
